const PizzaActions = {
  GET_DATA: 'PIZZA_GET_DATA',

  SELECTED: 'PIZZA_SELECTED',

  GET_DATA_SUCCESS: 'PIZZA_GET_DATA_SUCCESS',

  MINUS_QUANTITY: 'MINUS',

  ADD_QUANTITY: 'ADD',

  CLEAR: 'CLEAR',
};
export default PizzaActions;
